# generated by datamodel-codegen:
#   filename:  url-index.v1.json
#   timestamp: 2026-03-15T11:46:38+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class RemoteVersionEntry:
    assets: dict[str, str]
    prerelease: bool | None = False


@dataclass
class RemoteIndex:
    versions: dict[str, RemoteVersionEntry]
